#!/bin/bash

# Auto refreshing file tree
# The tree respects exclusions by VCS systems like git

# Author: x4e <x4e@protonmail.com>
# Dependencies: bash, ripgrep, tree, less, inotifywait

recursive_children () {
	local pids=$(ps -o pid= --ppid "$1")
	
	for pid in $pids; do
		recursive_children "$pid"
	done
	
	echo "$pids"
}

runTree() {
	clear
	rg --files | tree -C --fromfile --noreport | less -KQR~ --mouse --chop-long-lines
}

while [ true ]; do
	# Fork process and display tree
	runTree pidFile &
	
	# Wait for a change in the file tree, then refresh
	inotifywait -qr -e move -e move_self -e delete -e delete_self -e create -e unmount .
	
	# Recursively kill child processes
	kill $(recursive_children $$)
done
